export enum Region {
  RS11_BELGRADE = "RS11_BELGRADE",
  RS12_VOJVODINA = "RS12_VOJVODINA",
  RS21_WEST_SUMADIJA = "RS21_WEST_SUMADIJA",
  RS22_SOUTH_EAST = "RS22_SOUTH_EAST",
  RS23_KOSOVO_AND_METOHIJA = "RS23_KOSOVO_AND_METOHIJA"
}
