CREATE TABLE domain
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(64)                             NOT NULL UNIQUE,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_domain PRIMARY KEY (id)
);

CREATE TABLE subdomain
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    domain_id BIGINT                                  NOT NULL REFERENCES domain(id) ON DELETE CASCADE,
    code      VARCHAR(64)                             NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_subdomain PRIMARY KEY (id),
    UNIQUE (domain_id, code)
);

CREATE TABLE unit
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(32)                             NOT NULL,
    name VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_unit PRIMARY KEY (id)
);

CREATE TABLE indicator
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subdomain_id BIGINT                                  NOT NULL REFERENCES subdomain(id) ON DELETE CASCADE,
    code         VARCHAR(64)                             NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT,
    CONSTRAINT pk_indicator PRIMARY KEY (id),
    UNIQUE (subdomain_id, code)
);

CREATE TABLE dimension
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(64)                             NOT NULL,
    type           VARCHAR(16)                             NOT NULL,
    allowed_values JSONB,
    CONSTRAINT pk_dimension PRIMARY KEY (id),
    UNIQUE (name, type)
);

CREATE TABLE measure
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    indicator_id BIGINT                                  NOT NULL REFERENCES indicator(id) ON DELETE CASCADE,
    name         VARCHAR(64)                             NOT NULL,
    agg          VARCHAR(8)                              NOT NULL,
    unit_id      BIGINT REFERENCES unit(id),
    CONSTRAINT pk_measure PRIMARY KEY (id),
    UNIQUE (indicator_id, name)
);

CREATE TABLE indicator_dimension
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    indicator_id BIGINT                                  NOT NULL REFERENCES indicator(id) ON DELETE CASCADE,
    dimension_id BIGINT                                  NOT NULL REFERENCES dimension(id) ON DELETE CASCADE,
    ord          INTEGER                                 NOT NULL,
    CONSTRAINT pk_indicator_dimension PRIMARY KEY (id)
);

CREATE TABLE dataset
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT,
    status       VARCHAR(32),
    is_public    BOOLEAN                                 NOT NULL,
    created_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    indicator_id BIGINT REFERENCES indicator(id),
    CONSTRAINT pk_dataset PRIMARY KEY (id)
);

CREATE TABLE dataset_version
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dataset_id   BIGINT                                  NOT NULL,
    version      VARCHAR(32)                            NOT NULL,
    schema_json  OID,
    checksum     VARCHAR(255),
    row_count    BIGINT DEFAULT 0                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    published_at TIMESTAMP WITHOUT TIME ZONE,
    published_by VARCHAR(255),
    CONSTRAINT pk_dataset_version PRIMARY KEY (id)
);

CREATE TABLE import_job
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dataset_id        BIGINT                                  NOT NULL REFERENCES dataset(id) ON DELETE CASCADE,
    source_type       VARCHAR(16)                            NOT NULL,
    status            VARCHAR(16)                            NOT NULL,
    error_report_path TEXT,
    started_at        TIMESTAMP WITHOUT TIME ZONE,
    finished_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_import_job PRIMARY KEY (id)
);

CREATE TABLE data_point
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    indicator_id       BIGINT                                  NOT NULL REFERENCES indicator(id) ON DELETE CASCADE,
    dataset_version_id BIGINT                                  NOT NULL REFERENCES dataset_version(id) ON DELETE CASCADE,
    dims               JSONB                                   NOT NULL,
    measures           JSONB                                   NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    CONSTRAINT pk_data_point PRIMARY KEY (id)
);

ALTER TABLE dimension
    ADD CONSTRAINT uc_5bb16be3982153ba343655e76 UNIQUE (name, type);

ALTER TABLE subdomain
    ADD CONSTRAINT uc_617599cc2da373b360f61a5ac UNIQUE (domain_id, code);

ALTER TABLE indicator
    ADD CONSTRAINT uc_c2b3ed49676d6ba6ff910dfb5 UNIQUE (subdomain_id, code);

ALTER TABLE dataset
    ADD CONSTRAINT uc_dataset_name UNIQUE (name);

CREATE INDEX idx_dataset_indicator ON dataset(indicator_id);

ALTER TABLE domain
    ADD CONSTRAINT uc_domain_code UNIQUE (code);

ALTER TABLE measure
    ADD CONSTRAINT uc_f2e6105da93f7caf080071a12 UNIQUE (indicator_id, name);

ALTER TABLE unit
    ADD CONSTRAINT uc_unit_code UNIQUE (code);

ALTER TABLE dataset
    ADD CONSTRAINT FK_DATASET_ON_INDICATOR FOREIGN KEY (indicator_id) REFERENCES indicator (id);

ALTER TABLE dataset_version
    ADD CONSTRAINT FK_DATASET_VERSION_ON_DATASET FOREIGN KEY (dataset_id) REFERENCES dataset (id);

ALTER TABLE data_point
    ADD CONSTRAINT FK_DATA_POINT_ON_DATASET_VERSION FOREIGN KEY (dataset_version_id) REFERENCES dataset_version (id);

CREATE INDEX idx_data_point_dataset_version ON data_point (dataset_version_id);

ALTER TABLE data_point
    ADD CONSTRAINT FK_DATA_POINT_ON_INDICATOR FOREIGN KEY (indicator_id) REFERENCES indicator (id);

CREATE INDEX idx_data_point_indicator ON data_point (indicator_id);
CREATE INDEX idx_data_point_dims_gin ON data_point USING gin (dims jsonb_path_ops);
CREATE INDEX idx_data_point_measures_gin ON data_point USING gin ("measures" jsonb_path_ops);

ALTER TABLE import_job
    ADD CONSTRAINT FK_IMPORT_JOB_ON_DATASET FOREIGN KEY (dataset_id) REFERENCES dataset (id);

ALTER TABLE indicator_dimension
    ADD CONSTRAINT FK_INDICATOR_DIMENSION_ON_DIMENSION FOREIGN KEY (dimension_id) REFERENCES dimension (id);

ALTER TABLE indicator_dimension
    ADD CONSTRAINT FK_INDICATOR_DIMENSION_ON_INDICATOR FOREIGN KEY (indicator_id) REFERENCES indicator (id);

ALTER TABLE indicator
    ADD CONSTRAINT FK_INDICATOR_ON_SUBDOMAIN FOREIGN KEY (subdomain_id) REFERENCES subdomain (id);

ALTER TABLE measure
    ADD CONSTRAINT FK_MEASURE_ON_INDICATOR FOREIGN KEY (indicator_id) REFERENCES indicator (id);

ALTER TABLE measure
    ADD CONSTRAINT FK_MEASURE_ON_UNIT FOREIGN KEY (unit_id) REFERENCES unit (id);

ALTER TABLE subdomain
    ADD CONSTRAINT FK_SUBDOMAIN_ON_DOMAIN FOREIGN KEY (domain_id) REFERENCES domain (id);