spring.application.name=zavod-za-statistiku
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/zzs
spring.datasource.username=zzs
spring.datasource.password=zzs

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO

security.sso.enabled=false
security.sso.issuer=http://localhost:8081/realms/gov-suite
security.jwt.local-issuer=zzs-local
security.jwt.secret=to-change-in-the-future-dont-forget-lol-but-must-be-long-enough
security.jwt.access-ttl-seconds=1800
security.jwt.refresh-ttl-seconds=604800