# Spring basic config
spring.application.name=zavod-za-statistiku
server.port=8080

# DB setup
spring.datasource.url=jdbc:postgresql://localhost:5432/zzs
spring.datasource.username=zzs
spring.datasource.password=zzs

# JPA Setup
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

#Flyway Migration setup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Logger setup
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO

# SSO
auth0.domain=dev-7wsgpcp2kp2ul4ct.us.auth0.com
auth0.audience=https://api.shared
auth0.m2m.client.id=l6UhTDPlWXHJaZ77KudnCsaNa1dSTjvd
auth0.m2m.client.secret=bgKBi2ywzxsQrw784AWgtBLjWf6sxbnU3VIO-cMgnChp-GUSamjniNjiKo3DViVR
auth0.m2m.audience=https://dev-7wsgpcp2kp2ul4ct.us.auth0.com/api/v2/
auth0.m2m.db.connection=Email-Password-Authentication
auth0.m2m.roles.citizen=CITIZEN
auth0.m2m.roles.analyst=ANALYST
auth0.m2m.roles.admin=ADMIN
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${auth0.domain}
spring.security.oauth2.resourceserver.jwt.audiences=${auth0.audience}