# Spring basic config
spring.application.name=zavod-za-statistiku
server.port=8080

# DB setup
spring.datasource.url=jdbc:postgresql://localhost:5432/zzs
spring.datasource.username=zzs
spring.datasource.password=zzs

# JPA Setup
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

#Flyway Migration setup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Logger setup
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO

# Keycloak SSO
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/gov-realm
kc.server=http://localhost:8081
kc.realm=gov-realm
kc.admin.username=admin
kc.admin.password=admin
security.sso.issuer=http://localhost:8081/realms/gov-realm
security.sso.jwks-uri=http://localhost:8081/realms/gov-realm/protocol/openid-connect/certs
security.jwt.local-issuer=zzs-local
security.jwt.secret=to-change-in-the-future-dont-forget-lol-but-must-be-long-enough
security.jwt.access-ttl-seconds=1800
security.jwt.refresh-ttl-seconds=604800