# Spring basic config
spring.application.name=${APP_NAME}
server.port=${SERVER_PORT}

# DB setup
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Setup
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

#Flyway Migration setup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Logger setup
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO

# SSO
auth0.domain=${AUTH0_DOMAIN}
auth0.audience=${AUTH0_AUDIENCE}
auth0.m2m.client.id=${AUTH0_CLIENT_ID}
auth0.m2m.client.secret=${AUTH0_CLIENT_SECRET}
auth0.m2m.audience=${AUTH0_M2M_AUDIENCE}
auth0.m2m.db.connection=${AUTH0_DB}
auth0.m2m.roles.citizen=${ZZS_ROLE_CITIZEN}
auth0.m2m.roles.analyst=${ZZS_ROLE_ANALYST}
auth0.m2m.roles.admin=${ZZS_ROLE_ADMIN}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${JWT_AUDIENCE}